-- =========================================================
-- Drop Existing Objects (Updated List)
-- =========================================================
-- Drop Views first to remove dependencies
DROP VIEW IF EXISTS public.portfolio_fund_providers CASCADE; -- View depends on removed product_funds
DROP VIEW IF EXISTS public.latest_irr_values CASCADE;
DROP VIEW IF EXISTS public.latest_fund_valuations CASCADE;

-- Drop Tables (Order matters for FKs, CASCADE helps)
DROP TABLE IF EXISTS public.holding_activity_log CASCADE;
DROP TABLE IF EXISTS public.irr_values CASCADE;
DROP TABLE IF EXISTS public.fund_valuations CASCADE;
DROP TABLE IF EXISTS public.product_holdings CASCADE; -- New name
DROP TABLE IF EXISTS public.portfolio_funds CASCADE;
DROP TABLE IF EXISTS public.available_portfolio_funds CASCADE;
DROP TABLE IF EXISTS public.client_products CASCADE; -- New name
DROP TABLE IF EXISTS public.product_funds CASCADE; -- Removed table
DROP TABLE IF EXISTS public.available_funds CASCADE;
DROP TABLE IF EXISTS public.portfolios CASCADE;
DROP TABLE IF EXISTS public.available_portfolios CASCADE;
DROP TABLE IF EXISTS public.available_products CASCADE; -- Removed table
DROP TABLE IF EXISTS public.session CASCADE; -- Corrected name if 'sessions' was typo
DROP TABLE IF EXISTS public.authentication CASCADE;
DROP TABLE IF EXISTS public.available_providers CASCADE;
DROP TABLE IF EXISTS public.clients CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.fund_performance_history CASCADE; -- Removed table

-- =========================================================
-- Level 1 Tables (Generally no FK dependencies)
-- =========================================================

CREATE TABLE public.profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    first_name text NULL,
    last_name text NULL,
    email text NULL,
    profile_picture_url text NULL DEFAULT '/images/Companylogo2.png'::text,
    preferred_client_view text NULL DEFAULT 'list'::text,
    preferred_landing_page text NULL DEFAULT '/'::text,
    CONSTRAINT profiles_pkey PRIMARY KEY (id) -- Renamed constraint for consistency
) TABLESPACE pg_default;

CREATE TABLE public.available_providers (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text NULL,
    status text NOT NULL DEFAULT 'active'::text,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    theme_color text NULL,
    CONSTRAINT available_providers_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE public.clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text NULL DEFAULT ''::text,
    relationship text NULL DEFAULT ''::text,
    advisor text NULL,
    status text NULL DEFAULT 'active'::text,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT clients_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE public.available_funds (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fund_name text NULL,
    isin_number text NULL,
    risk_factor smallint NULL,
    fund_cost numeric(6, 2) NULL,
    status text NULL DEFAULT 'active'::text,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT available_funds_pkey PRIMARY KEY (id),
    CONSTRAINT available_funds_isin_number_key UNIQUE (isin_number)
) TABLESPACE pg_default;

-- Portfolio templates (Removed link to available_products)
CREATE TABLE public.available_portfolios (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    name text NULL,
    CONSTRAINT available_portfolios_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- =========================================================
-- Level 2 Tables (Depend on Level 1)
-- =========================================================

CREATE TABLE public.authentication (
    auth_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    password_hash text NULL,
    last_login timestamp WITH time zone NULL,
    updated_at timestamp WITH time zone NULL,
    profiles_id bigint NULL,
    CONSTRAINT authentication_pkey PRIMARY KEY (auth_id),
    CONSTRAINT authentication_profiles_id_fkey FOREIGN KEY (profiles_id) REFERENCES public.profiles (id)
) TABLESPACE pg_default;

CREATE TABLE public.session (
    session_id text NOT NULL,
    profiles_id bigint NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    expires_at timestamp WITH time zone NULL,
    last_activity timestamp WITH time zone NULL,
    CONSTRAINT session_pkey PRIMARY KEY (session_id),
    CONSTRAINT session_profiles_id_fkey FOREIGN KEY (profiles_id) REFERENCES public.profiles (id)
) TABLESPACE pg_default;

-- Portfolio instances (Added link back to template)
CREATE TABLE public.portfolios (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    portfolio_name text NULL,
    status text NULL DEFAULT 'active'::text,
    start_date date NULL,
    end_date date NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    original_template_id bigint NULL, -- Added FK
    CONSTRAINT portfolios_pkey PRIMARY KEY (id),
    CONSTRAINT portfolios_original_template_id_fkey FOREIGN KEY (original_template_id) REFERENCES public.available_portfolios (id) -- Constraint for added FK
) TABLESPACE pg_default;

-- Funds associated with portfolio templates
CREATE TABLE public.available_portfolio_funds (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    portfolio_id bigint NULL, -- FK to available_portfolios
    fund_id bigint NULL, -- FK to available_funds
    target_weighting numeric(5, 2) NULL, -- Note: This table still uses target_weighting, contrast with portfolio_funds below
    CONSTRAINT available_portfolio_funds_pkey PRIMARY KEY (id),
    CONSTRAINT available_portfolio_funds_fund_id_fkey FOREIGN KEY (fund_id) REFERENCES public.available_funds (id),
    CONSTRAINT available_portfolio_funds_portfolio_id_fkey FOREIGN KEY (portfolio_id) REFERENCES public.available_portfolios (id)
) TABLESPACE pg_default;

-- =========================================================
-- Level 3 Tables (Depend on Levels 1 & 2)
-- =========================================================

-- Replaced client_accounts, renamed constraints/indexes, added product_type
create table public.client_products (
  id bigint generated by default as identity not null,
  client_id bigint not null,
  product_name text null,
  status text not null default 'active'::text,
  start_date date not null,
  end_date date null,
  weighting numeric(5, 2) null,
  created_at timestamp with time zone not null default now(),
  plan_number text null,
  provider_id bigint null,
  product_type text null,
  portfolio_id bigint null,
  constraint client_products_pkey primary key (id),
  constraint client_products_client_id_fkey foreign KEY (client_id) references clients (id),
  constraint client_products_portfolio_id_fkey foreign KEY (portfolio_id) references portfolios (id),
  constraint client_products_provider_id_fkey foreign KEY (provider_id) references available_providers (id)
) TABLESPACE pg_default;

create index IF not exists idx_client_products_client_id on public.client_products using btree (client_id) TABLESPACE pg_default;

create index IF not exists idx_client_products_status on public.client_products using btree (status) TABLESPACE pg_default;

create index IF not exists idx_client_products_start_date on public.client_products using btree (start_date) TABLESPACE pg_default;

create index IF not exists idx_client_products_provider_id on public.client_products using btree (provider_id) TABLESPACE pg_default
where
  (provider_id is not null);

-- *** NEW definition for portfolio_funds as requested ***
-- Funds within specific portfolio instances (weighting column renamed from target_weighting)
CREATE TABLE public.portfolio_funds (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    portfolio_id bigint NOT NULL, -- FK to portfolios
    available_funds_id bigint NOT NULL, -- FK to available_funds
    weighting numeric(5, 2) NULL, -- Renamed from target_weighting
    start_date date NOT NULL,
    end_date date NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    amount_invested numeric(16, 2) NULL,
    CONSTRAINT portfolio_funds_pkey PRIMARY KEY (id),
    CONSTRAINT portfolio_funds_available_funds_id_fkey FOREIGN KEY (available_funds_id) REFERENCES public.available_funds (id),
    CONSTRAINT portfolio_funds_portfolio_id_fkey FOREIGN KEY (portfolio_id) REFERENCES public.portfolios (id)
) TABLESPACE pg_default;
-- *** END NEW definition for portfolio_funds ***

-- =========================================================
-- Level 4 Tables (Depend on Level 3)
-- =========================================================

-- Replaced account_holdings, renamed constraints/indexes and FK column
CREATE TABLE public.product_holdings (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_product_id bigint NOT NULL, -- Renamed FK column for clarity, FK to client_products
    portfolio_id bigint NULL, -- FK to portfolios
    status text NOT NULL DEFAULT 'active'::text,
    start_date date NOT NULL,
    end_date date NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT product_holdings_pkey PRIMARY KEY (id), -- Renamed constraint
    CONSTRAINT product_holdings_client_product_id_fkey FOREIGN KEY (client_product_id) REFERENCES public.client_products (id), -- Renamed constraint & references renamed column
    CONSTRAINT product_holdings_portfolio_id_fkey FOREIGN KEY (portfolio_id) REFERENCES public.portfolios (id) -- Renamed constraint
) TABLESPACE pg_default;

-- Valuations of specific funds within portfolio instances
CREATE TABLE public.fund_valuations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    portfolio_fund_id bigint NOT NULL, -- FK to portfolio_funds
    valuation_date timestamp WITHOUT time zone NOT NULL,
    value numeric(16, 2) NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT fund_valuations_pkey PRIMARY KEY (id),
    CONSTRAINT fund_valuations_portfolio_fund_id_fkey FOREIGN KEY (portfolio_fund_id) REFERENCES public.portfolio_funds (id)
) TABLESPACE pg_default;

-- =========================================================
-- Level 5 Tables (Depend on Level 4)
-- =========================================================


-- Activity log, references product_holdings now
CREATE TABLE public.holding_activity_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_holding_id bigint NOT NULL, -- References product_holdings
    portfolio_fund_id bigint NOT NULL, -- References portfolio_funds
    activity_timestamp date NOT NULL,
    activity_type text NOT NULL,
    amount numeric(16, 2) NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    related_fund bigint NULL, -- FK to portfolio_funds (e.g., for switches)
    CONSTRAINT holding_activity_log_pkey PRIMARY KEY (id),
    CONSTRAINT holding_activity_log_product_holding_id_fkey FOREIGN KEY (product_holding_id) REFERENCES public.product_holdings (id), -- Renamed constraint
    CONSTRAINT holding_activity_log_portfolio_fund_id_fkey FOREIGN KEY (portfolio_fund_id) REFERENCES public.portfolio_funds (id),
    CONSTRAINT holding_activity_log_related_fund_fkey FOREIGN KEY (related_fund) REFERENCES public.portfolio_funds (id)
) TABLESPACE pg_default;

CREATE TABLE public.irr_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    irr_result numeric(7, 2) NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    date timestamp WITHOUT time zone NULL,
    fund_id bigint NULL, -- FK to portfolio_funds
    fund_valuation_id bigint NULL, -- FK to fund_valuations
    CONSTRAINT irr_values_pkey PRIMARY KEY (id),
    CONSTRAINT irr_values_fund_id_fkey FOREIGN KEY (fund_id) REFERENCES public.portfolio_funds (id),
    CONSTRAINT irr_values_fund_valuation_id_fkey FOREIGN KEY (fund_valuation_id) REFERENCES public.fund_valuations (id)

) TABLESPACE pg_default;

-- =========================================================
-- Indexes (Updated List)
-- =========================================================


-- Indexes for client_products
CREATE INDEX IF NOT EXISTS idx_client_products_client_id ON public.client_products USING btree (client_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_client_products_status ON public.client_products USING btree (status) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_client_products_start_date ON public.client_products USING btree (start_date) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_client_products_provider_id ON public.client_products USING btree (provider_id) TABLESPACE pg_default WHERE (provider_id IS NOT NULL);

-- Indexes for product_holdings
CREATE INDEX IF NOT EXISTS idx_product_holdings_client_product_id ON public.product_holdings USING btree (client_product_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_product_holdings_portfolio_id ON public.product_holdings USING btree (portfolio_id) TABLESPACE pg_default WHERE (portfolio_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_product_holdings_status_dates ON public.product_holdings USING btree (status, start_date, end_date) TABLESPACE pg_default;

-- Indexes for holding_activity_log
CREATE INDEX IF NOT EXISTS idx_holding_activity_log_type_date ON public.holding_activity_log USING btree (activity_type, activity_timestamp) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_holding_activity_log_product_holding ON public.holding_activity_log USING btree (product_holding_id) TABLESPACE pg_default;

-- Indexes for portfolios
CREATE INDEX IF NOT EXISTS idx_portfolios_start_date ON public.portfolios USING btree (start_date) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_portfolios_original_template_id ON public.portfolios USING btree (original_template_id) TABLESPACE pg_default WHERE (original_template_id IS NOT NULL);

-- *** NEW Indexes for portfolio_funds as requested ***
CREATE INDEX IF NOT EXISTS idx_portfolio_funds_available_funds ON public.portfolio_funds USING btree (available_funds_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_portfolio_funds_amount_invested ON public.portfolio_funds USING btree (amount_invested) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_portfolio_funds_status ON public.portfolio_funds USING btree (end_date) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_portfolio_funds_dates_status ON public.portfolio_funds USING btree (start_date, end_date) TABLESPACE pg_default;
-- *** END NEW Indexes for portfolio_funds ***

-- Indexes for fund_valuations
CREATE UNIQUE INDEX IF NOT EXISTS idx_fund_valuations_unique ON public.fund_valuations (portfolio_fund_id, valuation_date) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_fund_valuations_date ON public.fund_valuations USING btree (valuation_date DESC) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_fund_valuations_portfolio_fund_date ON public.fund_valuations USING btree (portfolio_fund_id, valuation_date DESC) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_fund_valuations_value ON public.fund_valuations USING btree (value) TABLESPACE pg_default;
-- Removed potentially redundant index: idx_fund_valuations_fund_date

-- Indexes for irr_values
CREATE INDEX IF NOT EXISTS idx_irr_values_date ON public.irr_values USING btree (fund_id, date DESC) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_irr_values_fund_date_value ON public.irr_values USING btree (fund_id, date DESC, irr_result) TABLESPACE pg_default; -- Corrected column name
CREATE INDEX IF NOT EXISTS idx_irr_values_fund_valuation_id ON public.irr_values USING btree (fund_valuation_id) TABLESPACE pg_default;

-- Indexes for available_funds
CREATE INDEX IF NOT EXISTS idx_available_funds_status ON public.available_funds USING btree (status) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_available_funds_reporting ON public.available_funds USING btree (id, fund_name, status) TABLESPACE pg_default;

-- Indexes for available_portfolio_funds
CREATE INDEX IF NOT EXISTS idx_available_portfolio_funds_portfolio_id ON public.available_portfolio_funds USING btree (portfolio_id) TABLESPACE pg_default WHERE (portfolio_id IS NOT NULL);


-- Text Search Indexes (Optional - requires pg_trgm extension enabled by superuser)
-- CREATE EXTENSION IF NOT EXISTS pg_trgm;
-- CREATE INDEX IF NOT EXISTS idx_clients_name_trigram ON public.clients USING gin (name gin_trgm_ops);
-- CREATE INDEX IF NOT EXISTS idx_available_funds_name_trigram ON public.available_funds USING gin (fund_name gin_trgm_ops);


-- =========================================================
-- Views (Updated List)
-- =========================================================

-- View for latest IRR values (Corrected column reference)
CREATE VIEW public.latest_irr_values AS
SELECT DISTINCT
    ON (irr_values.fund_id) irr_values.fund_id,
    irr_values.irr_result AS irr_value, -- Corrected column name
    irr_values.date AS irr_date
FROM
    public.irr_values
ORDER BY
    irr_values.fund_id,
    irr_values.date DESC;

-- View for latest fund valuations
CREATE VIEW public.latest_fund_valuations AS
SELECT DISTINCT
    ON (fund_valuations.portfolio_fund_id) fund_valuations.id,
    fund_valuations.portfolio_fund_id,
    fund_valuations.valuation_date,
    fund_valuations.value
FROM
    public.fund_valuations
ORDER BY
    fund_valuations.portfolio_fund_id,
    fund_valuations.valuation_date DESC;

-- portfolio_fund_providers view removed as it depended on removed tables.
-- If a similar view is needed, it would need to be redesigned based on the new structure.

-- =========================================================
-- End of Script
-- =========================================================