-- =========================================================
-- Kingston's Portal - Step-by-Step Table Creation
-- This script creates tables one by one with proper dependency handling
-- =========================================================

-- First, let's see what tables already exist
SELECT 'Current tables:' as status;
SELECT table_name FROM information_schema.tables 
WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
ORDER BY table_name;

-- =========================================================
-- STEP 1: Create Level 1 Tables (No Dependencies)
-- =========================================================

-- Create profiles table
DROP TABLE IF EXISTS public.profiles CASCADE;
CREATE TABLE public.profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    first_name text NULL,
    last_name text NULL,
    email text NULL,
    profile_picture_url text NULL DEFAULT '/images/Companylogo2.png',
    preferred_client_view text NULL DEFAULT 'list',
    preferred_landing_page text NULL DEFAULT '/',
    CONSTRAINT profiles_pkey PRIMARY KEY (id)
);
SELECT 'Created profiles table' as status;

-- Create authentication table
DROP TABLE IF EXISTS public.authentication CASCADE;
CREATE TABLE public.authentication (
    auth_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    password_hash text NULL,
    profiles_id bigint NULL,
    CONSTRAINT authentication_pkey PRIMARY KEY (auth_id)
);
SELECT 'Created authentication table' as status;

-- Create session table
DROP TABLE IF EXISTS public.session CASCADE;
CREATE TABLE public.session (
    session_id text NOT NULL,
    profiles_id bigint NULL,
    expires_at timestamp WITH time zone NULL,
    CONSTRAINT session_pkey PRIMARY KEY (session_id)
);
SELECT 'Created session table' as status;

-- Create available_providers table
DROP TABLE IF EXISTS public.available_providers CASCADE;
CREATE TABLE public.available_providers (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text NULL,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    theme_color text NULL,
    CONSTRAINT available_providers_pkey PRIMARY KEY (id)
);
SELECT 'Created available_providers table' as status;

-- Create client_groups table
DROP TABLE IF EXISTS public.client_groups CASCADE;
CREATE TABLE public.client_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    advisor text NULL,
    status text NULL DEFAULT 'active',
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    name text NULL,
    type text NULL DEFAULT 'Family',
    CONSTRAINT client_groups_pkey PRIMARY KEY (id)
);
SELECT 'Created client_groups table' as status;

-- Create product_owners table
DROP TABLE IF EXISTS public.product_owners CASCADE;
CREATE TABLE public.product_owners (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    status text NULL DEFAULT 'active',
    firstname text NULL DEFAULT '',
    surname text NULL,
    known_as text NULL,
    CONSTRAINT product_owners_pkey PRIMARY KEY (id)
);
SELECT 'Created product_owners table' as status;

-- Create available_funds table
DROP TABLE IF EXISTS public.available_funds CASCADE;
CREATE TABLE public.available_funds (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fund_name varchar(60) NULL,
    isin_number text NULL,
    risk_factor smallint NULL,
    fund_cost numeric(6, 2) NULL,
    status text NULL DEFAULT 'active',
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT available_funds_pkey PRIMARY KEY (id),
    CONSTRAINT available_funds_isin_number_key UNIQUE (isin_number)
);
SELECT 'Created available_funds table' as status;

-- Create available_portfolios table
DROP TABLE IF EXISTS public.available_portfolios CASCADE;
CREATE TABLE public.available_portfolios (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    name text NULL,
    CONSTRAINT available_portfolios_pkey PRIMARY KEY (id)
);
SELECT 'Created available_portfolios table' as status;

-- =========================================================
-- STEP 2: Create Level 2 Tables (Depend on Level 1)
-- =========================================================

-- Create client_group_product_owners table
DROP TABLE IF EXISTS public.client_group_product_owners CASCADE;
CREATE TABLE public.client_group_product_owners (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_group_id bigint NULL,
    product_owner_id bigint NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT client_group_product_owners_pkey PRIMARY KEY (id)
);
SELECT 'Created client_group_product_owners table' as status;

-- Create template_portfolio_generations table
DROP TABLE IF EXISTS public.template_portfolio_generations CASCADE;
CREATE TABLE public.template_portfolio_generations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    available_portfolio_id bigint NULL,
    version_number integer NULL,
    generation_name text NULL,
    description text NULL,
    status text NULL DEFAULT 'active',
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT template_portfolio_generations_pkey PRIMARY KEY (id)
);
SELECT 'Created template_portfolio_generations table' as status;

-- Create available_portfolio_funds table
DROP TABLE IF EXISTS public.available_portfolio_funds CASCADE;
CREATE TABLE public.available_portfolio_funds (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    template_portfolio_generation_id bigint NULL,
    fund_id bigint NULL,
    target_weighting numeric(5, 2) NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT available_portfolio_funds_pkey PRIMARY KEY (id)
);
SELECT 'Created available_portfolio_funds table' as status;

-- Create portfolios table
DROP TABLE IF EXISTS public.portfolios CASCADE;
CREATE TABLE public.portfolios (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    portfolio_name text NULL,
    status text NULL DEFAULT 'active',
    start_date date NULL,
    end_date date NULL,
    template_generation_id bigint NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT portfolios_pkey PRIMARY KEY (id)
);
SELECT 'Created portfolios table' as status;

-- =========================================================
-- STEP 3: Create Level 3 Tables (Depend on Level 2)
-- =========================================================

-- Create client_products table
DROP TABLE IF EXISTS public.client_products CASCADE;
CREATE TABLE public.client_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id bigint NULL,
    product_name text NULL,
    product_type text NULL,
    status text NULL DEFAULT 'active',
    start_date date NULL,
    end_date date NULL,
    provider_id bigint NULL,
    portfolio_id bigint NULL,
    plan_number text NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT client_products_pkey PRIMARY KEY (id)
);
SELECT 'Created client_products table' as status;

-- Create product_owner_products table
DROP TABLE IF EXISTS public.product_owner_products CASCADE;
CREATE TABLE public.product_owner_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_owner_id bigint NULL,
    product_id bigint NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT product_owner_products_pkey PRIMARY KEY (id)
);
SELECT 'Created product_owner_products table' as status;

-- Create portfolio_funds table
DROP TABLE IF EXISTS public.portfolio_funds CASCADE;
CREATE TABLE public.portfolio_funds (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    portfolio_id bigint NULL,
    available_funds_id bigint NULL,
    target_weighting numeric(5, 2) NULL,
    amount_invested numeric(12, 2) NULL,
    start_date date NULL,
    end_date date NULL,
    status text NULL DEFAULT 'active',
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT portfolio_funds_pkey PRIMARY KEY (id)
);
SELECT 'Created portfolio_funds table' as status;

-- =========================================================
-- STEP 4: Create Level 4 Tables (Transaction/Valuation Data)
-- =========================================================

-- Create portfolio_fund_valuations table
DROP TABLE IF EXISTS public.portfolio_fund_valuations CASCADE;
CREATE TABLE public.portfolio_fund_valuations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    portfolio_fund_id bigint NULL,
    valuation_date date NULL,
    valuation numeric(12, 2) NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT portfolio_fund_valuations_pkey PRIMARY KEY (id)
);
SELECT 'Created portfolio_fund_valuations table' as status;

-- Create portfolio_valuations table
DROP TABLE IF EXISTS public.portfolio_valuations CASCADE;
CREATE TABLE public.portfolio_valuations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    portfolio_id bigint NULL,
    valuation_date date NULL,
    valuation numeric(12, 2) NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT portfolio_valuations_pkey PRIMARY KEY (id)
);
SELECT 'Created portfolio_valuations table' as status;

-- Create portfolio_fund_irr_values table
DROP TABLE IF EXISTS public.portfolio_fund_irr_values CASCADE;
CREATE TABLE public.portfolio_fund_irr_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fund_id bigint NULL,
    date date NULL,
    irr_result numeric(8, 4) NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT portfolio_fund_irr_values_pkey PRIMARY KEY (id)
);
SELECT 'Created portfolio_fund_irr_values table' as status;

-- Create portfolio_irr_values table
DROP TABLE IF EXISTS public.portfolio_irr_values CASCADE;
CREATE TABLE public.portfolio_irr_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    portfolio_id bigint NULL,
    date date NULL,
    irr_result numeric(8, 4) NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT portfolio_irr_values_pkey PRIMARY KEY (id)
);
SELECT 'Created portfolio_irr_values table' as status;

-- Create holding_activity_log table
DROP TABLE IF EXISTS public.holding_activity_log CASCADE;
CREATE TABLE public.holding_activity_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id bigint NULL,
    portfolio_fund_id bigint NULL,
    activity_type text NULL,
    amount numeric(12, 2) NULL,
    activity_timestamp timestamp WITH time zone NOT NULL DEFAULT now(),
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT holding_activity_log_pkey PRIMARY KEY (id)
);
SELECT 'Created holding_activity_log table' as status;

-- Create provider_switch_log table
DROP TABLE IF EXISTS public.provider_switch_log CASCADE;
CREATE TABLE public.provider_switch_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_product_id bigint NULL,
    previous_provider_id bigint NULL,
    new_provider_id bigint NULL,
    switch_date timestamp WITH time zone NULL,
    created_at timestamp WITH time zone NOT NULL DEFAULT now(),
    CONSTRAINT provider_switch_log_pkey PRIMARY KEY (id)
);
SELECT 'Created provider_switch_log table' as status;

-- =========================================================
-- Final Count
-- =========================================================
SELECT 'All tables created! Final count:' as status;
SELECT COUNT(*) as table_count FROM information_schema.tables 
WHERE table_schema = 'public' AND table_type = 'BASE TABLE';

SELECT 'Table list:' as status;
SELECT table_name FROM information_schema.tables 
WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
ORDER BY table_name;