-- =========================================================
-- Kingston's Portal - Add Missing User Page Presence Table
-- This script adds the user_page_presence table for concurrent user detection
-- =========================================================

-- Create the user_page_presence table
CREATE TABLE IF NOT EXISTS public.user_page_presence (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    page_identifier text NOT NULL,
    entered_at timestamp WITH time zone NULL DEFAULT now(),
    last_seen timestamp WITH time zone NULL DEFAULT now(),
    user_info jsonb NULL DEFAULT '{}'::jsonb,
    CONSTRAINT user_page_presence_pkey PRIMARY KEY (id),
    CONSTRAINT user_page_presence_user_id_page_identifier_key UNIQUE (user_id, page_identifier),
    CONSTRAINT user_page_presence_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles (id) ON DELETE CASCADE
);

SELECT 'Created user_page_presence table' as status;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_user_page_presence_page 
    ON public.user_page_presence USING btree (page_identifier);

CREATE INDEX IF NOT EXISTS idx_user_page_presence_last_seen 
    ON public.user_page_presence USING btree (last_seen);

CREATE INDEX IF NOT EXISTS idx_user_page_presence_user_page 
    ON public.user_page_presence USING btree (user_id, page_identifier);

SELECT 'Created user_page_presence indexes' as status;

-- Verify the table was created
SELECT 'Verification - Table exists:' as info;
SELECT EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_schema = 'public' 
    AND table_name = 'user_page_presence'
) as table_exists;

-- Show updated table count
SELECT 'Updated table count:' as info;
SELECT COUNT(*) as table_count 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_type = 'BASE TABLE';

-- Show updated index count
SELECT 'Updated index count:' as info;
SELECT COUNT(*) as index_count 
FROM pg_indexes 
WHERE schemaname = 'public'
AND indexname LIKE 'idx_%';

SELECT 'User page presence table added successfully!' as status;